import { useCallback, useEffect, useMemo, useState } from 'react'
import { LogOut, Sun } from 'lucide-react'
import Auth from './components/Auth'
import CalendarGrid from './components/CalendarGrid'
import DateBar from './components/DateBar'
import DayDetailsModal from './components/DayDetailsModal'
import ProjectModal from './components/ProjectModal'
import LessonModal from './components/LessonModal'
import StatsBar from './components/StatsBar'
import UnpaidPanel from './components/UnpaidPanel'
import { CARD_CLASS, TAX_PERCENT } from './constants'
import { getMonthMatrix, getPeriod, parseDateKey, periodLabel, todayKey } from './dateUtils'
import { computeStats } from './finance'
import { useTheme } from './hooks/useTheme'
import { supabase } from './supabaseClient'

const normalize = (row, type) => ({ ...row, type, date: type === 'lesson' ? row.lesson_date : row.start_date, amount: Number(row.amount) || 0, isPaid: row.is_paid === true, isGph: row.is_gph === true, instanceKey: `${type}_${row.id}_${type === 'lesson' ? row.lesson_date : row.start_date}` })
export default function App() {
  const [theme, setTheme] = useTheme(); const isDark = theme === 'dark'; const [session, setSession] = useState(null); const [loading, setLoading] = useState(true); const [projects, setProjects] = useState([]); const [lessons, setLessons] = useState([]); const [selectedKey, setSelectedKey] = useState(todayKey()); const [mode, setMode] = useState('day'); const [modal, setModal] = useState(null); const [dayDetailsKey, setDayDetailsKey] = useState(null)
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => subscription.unsubscribe() }, [])
  const fetchData = useCallback(async () => { if (!session?.user) return; const [p, l] = await Promise.all([supabase.from('projects').select('*').eq('user_id', session.user.id), supabase.from('lessons').select('*').eq('user_id', session.user.id)]); if (p.error || l.error) { console.error('[v0] data load failed', p.error || l.error); return } setProjects((p.data || []).map((row) => normalize(row, 'project'))); setLessons((l.data || []).map((row) => normalize(row, 'lesson'))) }, [session])
  useEffect(() => { if (session) fetchData() }, [session, fetchData])
  useEffect(() => { if (!projects.length && !lessons.length) setMode('day'); else { const saved = sessionStorage.getItem('gph_view_mode'); if (saved) setMode(saved) } }, [projects.length, lessons.length])
  const changeMode = (next) => { setMode(next); if (projects.length || lessons.length) sessionStorage.setItem('gph_view_mode', next) }
  const period = useMemo(() => getPeriod(mode, selectedKey), [mode, selectedKey]); const instances = useMemo(() => [...projects, ...lessons].filter((item) => item.date >= period.from && item.date <= period.to), [projects, lessons, period]); const byDate = useMemo(() => { const map = new Map(); instances.forEach((item) => map.set(item.date, [...(map.get(item.date) || []), item])); return map }, [instances]); const stats = useMemo(() => computeStats(instances), [instances]); const selectedDate = parseDateKey(selectedKey); const weeks = useMemo(() => getMonthMatrix(selectedDate.getFullYear(), selectedDate.getMonth()), [selectedDate]); const projectTemplates = useMemo(() => projects.slice(-6), [projects]); const lessonTemplates = useMemo(() => lessons.slice(-6), [lessons])
  const openCreate = (dateKey, type) => setModal({ type, instance: null, dateKey, key: Date.now() }); const openEdit = (instance) => setModal({ type: instance.type, instance, dateKey: instance.date, key: Date.now() }); const handleSave = async (data) => { if (!session?.user || !modal) return; const table = modal.type === 'lesson' ? 'lessons' : 'projects'; const payload = modal.type === 'lesson' ? { title: data.title, amount: data.amount, color: data.color, is_paid: data.isPaid, lesson_date: modal.dateKey, user_id: session.user.id } : { title: data.title, amount: data.amount, color: data.color, is_paid: data.isPaid, is_gph: data.isGph, start_date: modal.dateKey, end_date: modal.dateKey, user_id: session.user.id }; const result = modal.instance ? await supabase.from(table).update(payload).eq('id', modal.instance.id).eq('user_id', session.user.id).select().single() : await supabase.from(table).insert(payload).select().single(); if (result.error) { console.error('[v0] save failed', result.error); return } await fetchData(); setModal(null) }
  const handleDelete = async () => { if (!modal?.instance) return; const result = await supabase.from(modal.type === 'lesson' ? 'lessons' : 'projects').delete().eq('id', modal.instance.id).eq('user_id', session.user.id); if (!result.error) { await fetchData(); setModal(null) } }
  if (loading) return <div className='flex min-h-screen items-center justify-center'>Загрузка...</div>; if (!session) return <Auth />
  return <div className='min-h-screen font-sans text-stone-900 antialiased dark:text-zinc-100'><div className='mx-auto flex max-w-5xl flex-col gap-4 p-3 sm:gap-5 sm:p-6 lg:p-8'><header className='flex items-center justify-between pt-2'><div><h1 className='text-lg font-extrabold sm:text-xl'>Трекер доходов</h1><p className='text-xs text-stone-500'>{session.user.email}</p></div><div className='flex gap-2'><button type='button' onClick={() => setTheme(isDark ? 'light' : 'dark')} aria-label='Сменить тему' className='rounded-xl border p-2'><Sun className='size-4' /></button><button type='button' onClick={() => supabase.auth.signOut()} aria-label='Выйти' className='rounded-xl border p-2'><LogOut className='size-4' /></button></div></header><StatsBar stats={stats} periodLabelText={periodLabel(mode, selectedKey)} taxPercent={TAX_PERCENT} /><UnpaidPanel items={stats.unpaidList} onOpen={openEdit} isDark={isDark} /><section className={`${CARD_CLASS} p-2.5 sm:p-5`}><DateBar mode={mode} onModeChange={changeMode} selectedKey={selectedKey} onChange={setSelectedKey} /><div className='mt-3 sm:mt-4'><CalendarGrid mode={mode} weeks={weeks} selectedKey={selectedKey} byDate={byDate} isDark={isDark} onSelectDay={setDayDetailsKey} onOpenProject={openEdit} /></div></section></div>{dayDetailsKey && <DayDetailsModal dateKey={dayDetailsKey} instances={byDate.get(dayDetailsKey) || []} onClose={() => setDayDetailsKey(null)} onEdit={openEdit} onAddProject={() => { setDayDetailsKey(null); openCreate(dayDetailsKey, 'project') }} onAddLesson={() => { setDayDetailsKey(null); openCreate(dayDetailsKey, 'lesson') }} />}{modal && (modal.type === 'lesson' ? <LessonModal key={modal.key} dateKey={modal.dateKey} instance={modal.instance} templates={lessonTemplates} isDark={isDark} onClose={() => setModal(null)} onSave={handleSave} onDelete={handleDelete} /> : <ProjectModal key={modal.key} dateKey={modal.dateKey} instance={modal.instance} templates={projectTemplates} isDark={isDark} onClose={() => setModal(null)} onSave={handleSave} onDelete={handleDelete} />)}</div>
}
