import { useCallback, useEffect, useMemo, useState } from 'react';
import { LogOut, Moon, Sun } from 'lucide-react';
import Auth from './components/Auth';
import CalendarGrid from './components/CalendarGrid';
import DateBar from './components/DateBar';
import DayDetailsModal from './components/DayDetailsModal';
import ProjectModal from './components/ProjectModal';
import LessonModal from './components/LessonModal';
import StatsBar from './components/StatsBar';
import UnpaidPanel from './components/UnpaidPanel';
import { CARD_CLASS, TAX_PERCENT } from './constants';
import { getMonthMatrix, getPeriod, parseDateKey, periodLabel, todayKey } from './dateUtils';
import { computeStats } from './finance';
import { useTheme } from './hooks/useTheme';
import { supabase } from './supabaseClient';

function expandInstances(rows, period) { return rows.filter((x) => x.date >= period.from && x.date <= period.to).map((x) => ({ ...x, instanceKey: `${x.type}_${x.id}_${x.date}` })); }
function groupByDate(rows) { const map = new Map(); rows.forEach((x) => { if (!map.has(x.date)) map.set(x.date, []); map.get(x.date).push(x); }); return map; }

export default function App() {
  const [theme, setTheme] = useTheme(); const isDark = theme === 'dark'; const [session, setSession] = useState(null); const [loading, setLoading] = useState(true); const [projects, setProjects] = useState([]); const [lessons, setLessons] = useState([]); const [selectedKey, setSelectedKey] = useState(todayKey()); const [mode, setMode] = useState('day'); const [modal, setModal] = useState(null); const [dayDetailsKey, setDayDetailsKey] = useState(null);
  useEffect(() => { supabase.auth.getSession().then(({ data: { session } }) => { setSession(session); setLoading(false); }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => subscription.unsubscribe(); }, []);
  const fetchData = useCallback(async () => { if (!session?.user) return; const [{ data: p }, { data: l }] = await Promise.all([supabase.from('projects').select('*').eq('user_id', session.user.id), supabase.from('lessons').select('*').eq('user_id', session.user.id)]); setProjects((p || []).map((x) => ({ ...x, type: 'project', date: x.start_date, amount: Number(x.amount), isPaid: Boolean(x.is_paid) }))); setLessons((l || []).map((x) => ({ ...x, type: 'lesson', date: x.lesson_date, amount: Number(x.amount), isPaid: Boolean(x.is_paid) }))); }, [session]);
  useEffect(() => { if (session) fetchData(); }, [session, fetchData]);
  useEffect(() => { if (projects.length === 0 && lessons.length === 0) setMode('day'); else { const saved = sessionStorage.getItem('gph_view_mode'); if (saved) setMode(saved); } }, [projects.length, lessons.length]);
  const changeMode = (next) => { setMode(next); if (projects.length || lessons.length) sessionStorage.setItem('gph_view_mode', next); };
  const period = useMemo(() => getPeriod(mode, selectedKey), [mode, selectedKey]); const instances = useMemo(() => expandInstances([...projects, ...lessons], period), [projects, lessons, period]); const byDate = useMemo(() => groupByDate(instances), [instances]); const stats = useMemo(() => computeStats(instances), [instances]); const selectedDate = parseDateKey(selectedKey); const weeks = useMemo(() => getMonthMatrix(selectedDate.getFullYear(), selectedDate.getMonth()), [selectedDate]);
  const projectTemplates = useMemo(() => projects.slice(-6).map((x) => ({ title: x.title, amount: x.amount, color: x.color })), [projects]); const lessonTemplates = useMemo(() => lessons.slice(-6).map((x) => ({ title: x.title, amount: x.amount, color: x.color })), [lessons]);
  const openCreate = (dateKey, type = 'project') => setModal({ type, instance: null, dateKey, session: Date.now() }); const openEdit = (instance) => setModal({ type: instance.type, instance, dateKey: instance.date, session: Date.now() }); const closeModal = () => setModal(null); const openDay = (key) => setDayDetailsKey(key); const closeDay = () => setDayDetailsKey(null);
  const handleSave = async (data) => { if (!session?.user || !modal) return; const table = modal.type === 'lesson' ? 'lessons' : 'projects'; const payload = modal.type === 'lesson' ? { title: data.title, amount: data.amount, color: data.color, is_paid: data.isPaid, lesson_date: modal.dateKey } : { title: data.title, amount: data.amount, color: data.color, is_paid: data.isPaid, is_gph: data.isGph, start_date: modal.dateKey, end_date: modal.dateKey }; if (modal.instance) await supabase.from(table).update(payload).eq('id', modal.instance.id).eq('user_id', session.user.id); else await supabase.from(table).insert({ ...payload, user_id: session.user.id }); await fetchData(); closeModal(); };
  const handleDelete = async () => { if (!modal?.instance) return; await supabase.from(modal.type === 'lesson' ? 'lessons' : 'projects').delete().eq('id', modal.instance.id).eq('user_id', session.user.id); await fetchData(); closeModal(); };
  if (loading) return <div className="flex min-h-screen items-center justify-center">Загрузка...</div>; if (!session) return <Auth />;
  return <div className="min-h-screen font-sans text-stone-900 antialiased dark:text-zinc-100"><div className="mx-auto flex max-w-5xl flex-col gap-4 p-3 sm:gap-5 sm:p-6 lg:p-8"><header className="flex items-center justify-between pt-2"><div><h1 className="text-lg font-extrabold sm:text-xl">Трекер доходов</h1><p className="text-xs text-stone-500">{session.user.email}</p></div><div className="flex gap-2"><button type="button" onClick={() => setTheme(isDark ? 'light' : 'dark')} aria-label="Сменить тему" className="rounded-xl border p-2"><Sun className="h-4 w-4" /></button><button type="button" onClick={() => supabase.auth.signOut()} aria-label="Выйти" className="rounded-xl border p-2"><LogOut className="h-4 w-4" /></button></div></header><StatsBar stats={stats} periodLabelText={periodLabel(mode, selectedKey)} taxPercent={TAX_PERCENT} /><UnpaidPanel items={stats.unpaidList} onOpen={openEdit} isDark={isDark} /><section className={`${CARD_CLASS} p-2.5 sm:p-5`}><DateBar mode={mode} onModeChange={changeMode} selectedKey={selectedKey} onChange={setSelectedKey} /><div className="mt-3 sm:mt-4"><CalendarGrid mode={mode} weeks={weeks} selectedKey={selectedKey} byDate={byDate} isDark={isDark} onSelectDay={openDay} onOpenProject={openEdit} /></div></section></div>{dayDetailsKey && <DayDetailsModal dateKey={dayDetailsKey} instances={byDate.get(dayDetailsKey) || []} onClose={closeDay} onEdit={openEdit} onAddProject={() => { closeDay(); openCreate(dayDetailsKey, 'project'); }} onAddLesson={() => { closeDay(); openCreate(dayDetailsKey, 'lesson'); }} />}{modal && (modal.type === 'lesson' ? <LessonModal key={modal.session} dateKey={modal.dateKey} instance={modal.instance} templates={lessonTemplates} isDark={isDark} onClose={closeModal} onSave={handleSave} onDelete={handleDelete} /> : <ProjectModal key={modal.session} dateKey={modal.dateKey} instance={modal.instance} templates={projectTemplates} isDark={isDark} onClose={closeModal} onSave={handleSave} onDelete={handleDelete} />)}</div>;
}
